/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ShareShareIdRouteImport } from './routes/share.$shareId'
import { Route as ApiFeedbackRouteImport } from './routes/api/feedback'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks.stripe'
import { Route as ApiWebhooksSlackRouteImport } from './routes/api/webhooks.slack'
import { Route as ApiPublicAdminRunMigrationRouteImport } from './routes/api/public/admin-run-migration'
import { Route as ApiDatasourcesProcessRouteImport } from './routes/api/datasources.process'
import { Route as ApiConnectorsCallbackRouteImport } from './routes/api/connectors.callback'
import { Route as ApiChatStreamRouteImport } from './routes/api/chat.stream'
import { Route as AppCIdRouteImport } from './routes/_app.c.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksSlackRoute = ApiWebhooksSlackRouteImport.update({
  id: '/api/webhooks/slack',
  path: '/api/webhooks/slack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminRunMigrationRoute =
  ApiPublicAdminRunMigrationRouteImport.update({
    id: '/api/public/admin-run-migration',
    path: '/api/public/admin-run-migration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDatasourcesProcessRoute = ApiDatasourcesProcessRouteImport.update({
  id: '/api/datasources/process',
  path: '/api/datasources/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectorsCallbackRoute = ApiConnectorsCallbackRouteImport.update({
  id: '/api/connectors/callback',
  path: '/api/connectors/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/api/chat/stream',
  path: '/api/chat/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCIdRoute = AppCIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/billing': typeof AppBillingRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/c/$id': typeof AppCIdRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/api/connectors/callback': typeof ApiConnectorsCallbackRoute
  '/api/datasources/process': typeof ApiDatasourcesProcessRoute
  '/api/public/admin-run-migration': typeof ApiPublicAdminRunMigrationRoute
  '/api/webhooks/slack': typeof ApiWebhooksSlackRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/billing': typeof AppBillingRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/': typeof AppIndexRoute
  '/c/$id': typeof AppCIdRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/api/connectors/callback': typeof ApiConnectorsCallbackRoute
  '/api/datasources/process': typeof ApiDatasourcesProcessRoute
  '/api/public/admin-run-migration': typeof ApiPublicAdminRunMigrationRoute
  '/api/webhooks/slack': typeof ApiWebhooksSlackRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/billing': typeof AppBillingRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/c/$id': typeof AppCIdRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/api/connectors/callback': typeof ApiConnectorsCallbackRoute
  '/api/datasources/process': typeof ApiDatasourcesProcessRoute
  '/api/public/admin-run-migration': typeof ApiPublicAdminRunMigrationRoute
  '/api/webhooks/slack': typeof ApiWebhooksSlackRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/billing'
    | '/api/feedback'
    | '/share/$shareId'
    | '/c/$id'
    | '/api/chat/stream'
    | '/api/connectors/callback'
    | '/api/datasources/process'
    | '/api/public/admin-run-migration'
    | '/api/webhooks/slack'
    | '/api/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/billing'
    | '/api/feedback'
    | '/share/$shareId'
    | '/'
    | '/c/$id'
    | '/api/chat/stream'
    | '/api/connectors/callback'
    | '/api/datasources/process'
    | '/api/public/admin-run-migration'
    | '/api/webhooks/slack'
    | '/api/webhooks/stripe'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/billing'
    | '/api/feedback'
    | '/share/$shareId'
    | '/_app/'
    | '/_app/c/$id'
    | '/api/chat/stream'
    | '/api/connectors/callback'
    | '/api/datasources/process'
    | '/api/public/admin-run-migration'
    | '/api/webhooks/slack'
    | '/api/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ShareShareIdRoute: typeof ShareShareIdRoute
  ApiChatStreamRoute: typeof ApiChatStreamRoute
  ApiConnectorsCallbackRoute: typeof ApiConnectorsCallbackRoute
  ApiDatasourcesProcessRoute: typeof ApiDatasourcesProcessRoute
  ApiPublicAdminRunMigrationRoute: typeof ApiPublicAdminRunMigrationRoute
  ApiWebhooksSlackRoute: typeof ApiWebhooksSlackRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/slack': {
      id: '/api/webhooks/slack'
      path: '/api/webhooks/slack'
      fullPath: '/api/webhooks/slack'
      preLoaderRoute: typeof ApiWebhooksSlackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-run-migration': {
      id: '/api/public/admin-run-migration'
      path: '/api/public/admin-run-migration'
      fullPath: '/api/public/admin-run-migration'
      preLoaderRoute: typeof ApiPublicAdminRunMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/datasources/process': {
      id: '/api/datasources/process'
      path: '/api/datasources/process'
      fullPath: '/api/datasources/process'
      preLoaderRoute: typeof ApiDatasourcesProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connectors/callback': {
      id: '/api/connectors/callback'
      path: '/api/connectors/callback'
      fullPath: '/api/connectors/callback'
      preLoaderRoute: typeof ApiConnectorsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/stream': {
      id: '/api/chat/stream'
      path: '/api/chat/stream'
      fullPath: '/api/chat/stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/c/$id': {
      id: '/_app/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof AppCIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCIdRoute: typeof AppCIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppIndexRoute: AppIndexRoute,
  AppCIdRoute: AppCIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ShareShareIdRoute: ShareShareIdRoute,
  ApiChatStreamRoute: ApiChatStreamRoute,
  ApiConnectorsCallbackRoute: ApiConnectorsCallbackRoute,
  ApiDatasourcesProcessRoute: ApiDatasourcesProcessRoute,
  ApiPublicAdminRunMigrationRoute: ApiPublicAdminRunMigrationRoute,
  ApiWebhooksSlackRoute: ApiWebhooksSlackRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
